### ISSUE TITLE
[Feature Request] Implement slack bot with sentry

### ISSUE THREAD

**Issue by hcho112** [near/fast-auth-signer#104]
**Is your feature request related to a problem? Please describe.**
Once PR #103 gets merged, we should integrate it with slack bot to get realtime report to our slack channel. 

**Describe the solution you'd like**
integrate sentry slack bot to our channel (new or existing)

**Describe alternatives you've considered**
email notification to specific group of engineers (not so ideal)

**Additional context**
This is a to make sure we get near real time error tracking around fast-auth

**Comment by hcho112** [comment]
Initial integration has been done to one of our internal channel. Will close this when we start to see more notification(s)

**Comment by volovyks** [comment]
We see a lot of notifications now :) probably this one is done
