### ISSUE TITLE
Check number of keys (LAKs and FAKs), let users select one to remove

### ISSUE THREAD

**Issue by DavidM-D** [near/fast-auth-signer#13]
1. Fetch the user's `publicKey`s
2. Fetch the recovery publicKey from the recovery service
3. Fetch the user's firestore `devices` collection for a list with the schema: 
```typescript
{
  country: string;
  device: string;
  os: string;
  publicKeys: string[];
}[]
```
3. Display a selection UI using the metadata and delete the publicKeys the user selects. Hide the recovery key from selection UI

**Comment by hcho112** [comment]
with discussion from @esaminu we have added more details to this ticket. 

Create `/devices` route
