### ISSUE TITLE
[BUG] Account not found

### ISSUE THREAD

**Issue by Pessina** [near/fast-auth-signer#149]
I'm encountering an error when attempting to sign in with my newly created account on near.org. The error message displayed is "Account not found, please create an account and try again," and the URL is: https://near.org/signin?reason=Account+not+found%2C+please+create+an+account+and+try+again.

Steps to reproduce the issue in Chrome:

- Create an account on near.org.
- Receive a confirmation email from Firebase.
- Click on the link in the email to register your passkey.
- After successful account creation, you will be logged into near.org.
- Log out of the account.
- Try signing in again using the email of the newly created account.
- Instead of asking for your passkeys, the system sends another Firebase login email.
- Click on the link in the email and complete the login process.
- Get redirected to the error page with the URL https://near.org/signin?reason=Account+not+found%2C+please+create+an+account+and+try+again.

As a result, I am unable to access my newly created account.

Video with steps to reproduce: https://drive.google.com/file/d/1RHGmX6hOBZH0PmHkDvR1sroYs4lGLdqQ/view?usp=drive_link

**Comment by DavidM-D** [comment]
Are these two bugs related?
https://github.com/near/fast-auth-signer/issues/170
