### ISSUE TITLE
Problems with `yarn start` on localhost

### ISSUE THREAD

**Issue by johnnynanjiang** [near/fast-auth-signer#253]
`yarn start` on localhost is pointing to `https://api.kitwallet.app` and getting error `blocked by CORS policy: No 'Access-Control-Allow-Origin' header`

Should `yarn start` be pointing to testnet (`https://testnet-api.kitwallet.app`) and CORS policy allow localhost?

![image](https://github.com/near/fast-auth-signer/assets/11918567/6068cae2-dda5-48a0-b15d-45f4364aaad3)

**Comment by johnnynanjiang** [comment]
`NETWORK_ID=testnet yarn start` solved the problem above

**Comment by johnnynanjiang** [comment]
The app is behaving like this on localhost, is it expected?

https://github.com/near/fast-auth-signer/assets/11918567/459f5b98-89e9-4f68-9ed9-74f413de3314

**Comment by hcho112** [comment]
@johnnynanjiang 
I just pulled our latest main branch and run it locally with `NETWORK_ID=testnet yarn start` on `YOURDIRECTORY/fast-auth-signer/packages/near-fast-auth-signer` and I got:
<img width="1622" alt="image" src="https://github.com/near/fast-auth-signer/assets/6027014/bd0960bf-4367-4511-8e75-5e8ee558cbbb">

It should still work. The account you have used above, have you created them with fast-auth first? if not, you should create via `http://localhost:3000/create-account`.

**Comment by johnnynanjiang** [comment]
Thanks @hcho112 

I think the UI is a bit confusing, I got `signed in` button in RED, then it turned BLUE after seconds. 

There is no clear message saying everything is ok, somehow I assume this is the expected behaviour, is that correct?

**Comment by hcho112** [comment]
@johnnynanjiang what you need to understand is that this repo has to be used in a specific way. Not just on it's own.
(Signed in button on red to blue was just there for quick UI check. In real world it is not being used. )

Check how it is being used on [here](https://test.near.org/)

In terms of implementation, how it is being used is:
test.near.org (running on top of https://github.com/near/near-discovery) is using 
setupFastAuthWallet from (https://github.com/near/near-fastauth-wallet)
which it points to [testnet](https://wallet.testnet.near.org/fastauth) or [mainnet](https://wallet.near.org/fastauth)

It may look overly complicated, but it is designed in a way that it naturally integrates with existing NEAR applications and multiple vendors. 

Please take a look and let us know if you struggle to understand the flow. Meanwhile, if this issue of problem with yarn start on local environment is not an actual issue, will close the issue shortly

**Comment by johnnynanjiang** [comment]
Thanks @hcho112 for giving me some context, it is helpful for me as a newcomer.

Yes I think it is not a real issue, just some confusion for me to try it out. I believe it would be much clearer overtime with help from community members like you, which is great.

**Comment by hcho112** [comment]
@johnnynanjiang 
Thank you for quick feedback and we actually feel sorry that you had to go through bad experience. We are well aware of lack of documentation around fast-auth repos and we are planning to improve them shortly. Thank you for being patient and please feel free to ask questions.
