### ISSUE TITLE
UX for Sign In with a FastAuth Account

### ISSUE THREAD

**Issue by DavidM-D** [near/fast-auth-signer#27]
Design for Sign In flow, adding a new device or browser to a FastAuth Account.

### [Figma Design Link](https://www.figma.com/file/oK9aMWVmjoXHRUcBUFmFvT/Create-an-Account?type=design&node-id=2480%3A670426&mode=design&t=AmFJjq2fBUl1mhsN-1)

![Image](https://github.com/near/fast-auth-signer/assets/103140483/3bce110b-b059-4042-ab43-7994c07a9cd8)

**Comment by nall-near** [comment]
Added design and Figma Link.
