### ISSUE TITLE
Data Erasure Requests

### ISSUE THREAD

**Issue by Ishatt** [near/fast-auth-signer#64]
Could we please erase PII (like email data on FastAuth) for the following individuals who have requested it?

```[tasklist]
### 3 Requests:
- [ ] https://github.com/near/pagoda-support/issues/3
- [ ] https://github.com/near/pagoda-support/issues/1
- [ ] https://github.com/near/pagoda-support/issues/2
```

**Comment by Ishatt** [comment]
@trechriron @DavidM-D

**Comment by Ishatt** [comment]
@DavidM-D @trechriron Let me know an estimate for closing this out- we have follow up requests.

**Comment by diogoortega** [comment]
All deletion requests have been completed (additional details on each individual ticket).
