### ISSUE TITLE
Add [signMessage] endpoint 

### ISSUE THREAD

**Issue by Ishatt** [near/fast-auth-signer#67]
For the Fractal idOS flow to work for FastAuth users, the FastAuth SDK needs to be integrated into the wallet on [near.org]. We need the sign message endpoint for this to work. 

Please provide Isha with an estimated level of effort/ timeline to add this. We want to launch this at NEARCON officially but would like this a little beforehand. 

Figma Flow: [https://www.figma.com/proto/dmfi3WIjvfyoXBVaPdqRvt/IDOS?page-id=153%3A8850&type=des[…]=scale-down-width&starting-point-node-id=244%3A36117&hide-ui=1](https://www.figma.com/proto/dmfi3WIjvfyoXBVaPdqRvt/IDOS?page-id=153%3A8850&type=design&node-id=153-10145&viewport=661%2C583%2C0.06&t=NJa0hmKQ0s5vGMLG-8&scaling=scale-down-width&starting-point-node-id=244%3A36117&hide-ui=1)

**Comment by Ishatt** [comment]
@tidus974

**Comment by charleslavon** [comment]
A wallet's support for signmessage can be tested in the UI @ [near.org/signmessage](https://near.org/signMessage)

**Comment by tonebonekone** [comment]
NEARTasks +1 on this feature request. We'd like to integrate it before NEARCON is possible. TY!

**Comment by diogoortega** [comment]
@esaminu could you help us estimate the effort to implement this?

**Comment by diogoortega** [comment]
@hcho112 could you help us estimate the effort to implement this?

**Comment by DavidM-D** [comment]
From @esaminu 

It should take about a 1.5 days of work, we should add a new /sign-message route on the signer app and if auth state is false we should redirect to failure_url if not we should use the FAK from biometric to sign the message per the NEP and redirect back to callbackUrl after the signing. We should also postmessage with the response similar to /sign. We can use FastAuthWalletConnection to open the iframe at the new route and handle the response similar to requestSignTransactions
