### ISSUE TITLE
Move passkey registration to the end of account creation flow

### ISSUE THREAD

**Issue by nall-near** [near/fast-auth-signer#84]
### Description
To streamline account creation, move the passkey registration to the end of the flow. This allows the user to complete tasks within the signer app at the same time, account creation and passkey registration.

#### [Figma Link](https://www.figma.com/file/oK9aMWVmjoXHRUcBUFmFvT/Create-an-Account?type=design&node-id=4200-104822&mode=design&t=THqwAI1K3qoVYG4W-4)
![image](https://github.com/near/fast-auth-signer/assets/103140483/1332f1ad-734c-4bda-a6eb-99db2c978ee5)

**Comment by Pessina** [comment]
PR: https://github.com/near/fast-auth-signer/pull/135
